#! /usr/bin/tcsh
################################################################################
#
# score - Rev 1.0
# Copyright (C) 2021 by Joseph B. Attili, aa2il AT arrl DOT net
#
# Script to run cabrillo converter/scoring code.
#
################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
################################################################################

# Select a contest
set CONTEST=""

#set CONTEST="cwt"
#set CONTEST="cwopen"
#set CONTEST="sst"
#set CONTEST="cqww"
#set CONTEST="cwss"              # Sweepstakes
#set CONTEST="arrl_dx"
#set CONTEST="fd"               # Field Day  - worked in 2020
#set CONTEST="cqp"
#set CONTEST="naqpcw"
#set CONTEST="naqprtty"
#set CONTEST="wwdigi"
#set CONTEST="wpx"
#set CONTEST="arrl_10m"
#set CONTEST="vhf"                # ARRL VHF - Jan, June & Sept.
#set CONTEST="iaru"
#set CONTEST="cols13"            # 13 colonies special event - worked in 2021
#set CONTEST="sats"              # Satellites worked  - worked in 2021
#set CONTEST="ft8ru"
#set CONTEST="rttyru"             # ARRL RTTY Round-up

echo " "
set d=`date`
echo d=$d
echo d1=$d[1]
if( X$CONTEST == "X" && $d[1] == "Mon" )then
    set CONTEST="mst"
else if( X$CONTEST == "X" && $d[1] == "Wed" )then
    set CONTEST="cwt"
else if( X$CONTEST == "X" && ($d[1] == "Fri" || $d[1] == "Sun"))then
    set CONTEST="sst"
else
    echo " "
    echo "--- Can't figure out contest ---"
    echo " "
    exit
endif
echo $CONTEST

################################################################################

echo cabrillo.py -$CONTEST
cabrillo.py -$CONTEST

# cabrillo.py -cqp -hist lotwreport.adi


# Need to bring the rest of these into this if-then-else structure

# ARRL 10 meter
#cabrillo.py -ten

# NAQP - CW wasn't tested but should work, RTTY was tested
#cabrillo.py -naqpcw 
#cabrillo.py -naqprtty

# CQ WW RTTY
#cabrillo.py -wwrtty

# CQ WW CW - seems to work in 2020
#cabrillo.py -wwcw

# WW Digi  - Code still needs to be converted 
#cabrillo.py -wwdigi

# Makroten
#cabrillo.py -mak


