#! /usr/bin/tcsh
################################################################################
#
# score - Rev 1.0
# Copyright (C) 2021-5 by Joseph B. Attili, joe DOT aa2il AT gmail DOT com
#
# Script to run cabrillo converter/scoring code.
#
################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
################################################################################

#pushd ~/Python/contest

# Select a contest - Start putting them a chornological order ...
set CONTEST=""
#set CONTEST="cwt"                # CWops CWT
#set CONTEST="sst"                # K1USN Slow Speed Test
#set CONTEST="mst"                # ICWC Medium Speed Test

#set CONTEST="rttyru"             # ARRL RTTY Round-up
#set CONTEST="naqpcw"             # North American QSO Party CW
#set CONTEST="naqprtty"           # North American QSO Party RTTY
#set CONTEST="cq160m"             # CQ 160m CW
#set CONTEST="arrl_dx"            # ARRL Intl DX - both CW & SSB versions
#set CONTEST="foc"                # FOC BW

#set CONTEST="cwopen"             # CWops CW Open
#set CONTEST="cqwwcw"             # CQ WW CW
#set CONTEST="cqwwrtty"           # CQ WW RTTY
#set CONTEST="cwss"               # ARRL Sweepstakes
#set CONTEST="fd"                 # Winter or ARRL Field Day
#set CONTEST="cqp"                # Commiefornia QSO Party
#set CONTEST="state"              # State (other than CA) QSO Party
#set CONTEST="wwdigi"             # CQ WW Digi 
#set CONTEST="cqmm"                # CQMM
#set CONTEST="wpxcw"              # CQ WPX CW
#set CONTEST="vhf"                # ARRL VHF - Jan, June & Sept.
#set CONTEST="vhfss"              # VHF Spring Sprint
#set CONTEST="cqvhf"              # CQ WW VHF - July
#set CONTEST="fall50"             # SE VHF Soc -  50 MHz Fall Sprint - August - svhfs.org
#set CONTEST="namss"              # NA Meteor Scatter Sprint - August
#set CONTEST="iaru"               # IRAU HF Champs
#set CONTEST="cols13"             # 13 colonies special event - worked in 2021
#set CONTEST="sats"               # Satellites worked  - worked in 2021
#set CONTEST="ftru"               # FT Round-up - December
#set CONTEST="ten"                 # ARRL 10-meter 
#set CONTEST="rac"                 # RAC Summer and Winter Contests
#set CONTEST="mak"                 # Makrothen rtty
#set CONTEST="ocdx"                 # Oceania DX CW

# Select specific CWT/MST sessions or State QSO party here
set SESSION=""
#set SESSION="19"                 # Session start time
#set SESSION="03"                 # Session start time
#set SESSION=3                    # CW Open Session 1, 2 or 3
#set SESSION="W7"                  # State QSO party

set TIME_LIMIT=""
set TIME_LIMIT="-nograph"
#set TIME_LIMIT="-nograph -limit 10"               # NAQP

# Select input file
set LOG_FILE=""
#set LOG_FILE="-i NAQP.csv"  
#set LOG_FILE="-i NAQP.adif"
#set LOG_FILE="-i CWOPEN.csv"
#set LOG_FILE="-i ../pyKeyer/AA2IL.adif"       
if( ("X$CONTEST" == "Xstate") && ("X${LOG_FILE}" == "X") )then
    set LOG_FILE="-i STATE_QPs.csv"                 # One or more state QPs
    set LOG_FILE="-i STATE_QPs.adif"                 # One or more state QPs
endif
echo LOG_FILE=$LOG_FILE
#exit

# Most of time, I'm running assited
set ASSISTED=""
set ASSISTED="-assisted"
#set ASSISTED="-hist ../pyKeyer/CQP/lotwreport.adi"

# Figure out if we're in a weekly practice contests
echo " "
set d=`date -u +"%a %H"`
if( X$CONTEST == "X" )then
    set day  = $d[1]
    set hour = $d[2]
    echo day=$day             hour=$hour
    if( $day == "Mon" )then
        if ( (($hour >= 12) && ($hour <= 18)) || (($hour >= 18) && ($hour <= 23)) )then
            set CONTEST="mst"
        else if( $hour <= 12 )then
            set CONTEST="sst"
        endif
    else if( $day == "Tue" )then
        if ( ($hour >= 1) && ($hour <= 23) )then
            set CONTEST="mst"
        endif
    else if( $day == "Wed" )then
        if( (($hour >= 12) && ($hour <= 18)) || (($hour >= 18) && ($hour <= 23)) )then
            set CONTEST="cwt"
        endif
    else if( $day == "Thu" )then
        if( (($hour >= 2) && ($hour <= 6)) || (($hour >= 6) && ($hour <= 23)) )then
            set CONTEST="cwt"
        endif
    else if( ($day == "Fri") && ($hour >= 1) && ($hour <= 12) )then
        set CONTEST="sprint"
    else if( ($day == "Fri") && ($hour >= 13) && ($hour <= 23) )then
        set CONTEST="sst"
    else if( ($day == "Sat") && ($hour >= 23) )then
        set CONTEST="sst"
    endif
endif
if( X$CONTEST == "X" )then
        echo " "
        echo "--- Can't figure out contest - Giving up \!\!\! ---"
        echo " "
        exit 1
endif
echo CONTEST=$CONTEST     SESSION=$SESSION
#exit 0

################################################################################

echo " "
set EXE="~/Python/contest/cabrillo.py"
pwd
echo $EXE -$CONTEST $SESSION $TIME_LIMIT $ASSISTED $LOG_FILE
$EXE -$CONTEST $SESSION  $TIME_LIMIT $ASSISTED $LOG_FILE

# cabrillo.py -cqp -hist lotwreport.adi

